// Code generated by hertz generator.

package task

import (
	"github.com/cloudwego/hertz/pkg/app"
	"work3/biz/middleware"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.JwtMiddleware.MiddlewareFunc(),
	}
}

func _taskMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addtaskMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatetaskMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletetaskMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletetaskbystatusMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _querylistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _querytasklistbykeywordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _querytaskbystatusMw() []app.HandlerFunc {
	// your code...
	return nil
}
