// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"work3/biz/dal"
	"work3/biz/middleware"
)

func Init() {
	dal.Init()
	middleware.Init()
}

func main() {
	Init()

	h := server.Default()

	register(h)
	h.Spin()
}
